### ISSUE TITLE
Occasional 'Malformed response cannot be parsed' error with Twitter sign-in

### ISSUE THREAD

**Issue by maryam-abdullah** [firebase/firebaseui-web#244]
When signing in with Twitter, I sometimes get the error below:

> POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=<my_key> 400 ()
> [firebaseui] Internal error: {"error":{"errors":[{"domain":"global","reason":"invalid","message":"Malformed response cannot be parsed"}],"code":400,"message":"Malformed response cannot be parsed"}}

> {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Malformed response cannot be parsed"
   }
  ],
  "code": 400,
  "message": "Malformed response cannot be parsed"
 }
}

And then, when I sign in again, it does successfully.
Previously, everything was working fine.

Thanks in advance.

**Comment by bojeil-google** [comment]
Hey @maryam-abdullah I will relay your issue to the Firebase Auth backend team. Thanks,

**Comment by maryam-abdullah** [comment]
Thank you.

**Comment by rhroyston** [comment]
I had this same issue using Twitter Oauth, namely Malformed response cannot be parsed message.

The fix was for me to sign out of my Twitter account that has the oauth app then sign back in. That seems to be the fix for me.

**Comment by calchulus** [comment]
Also having the same problem

**Comment by bojeil-google** [comment]
This should be fixed.

**Comment by Surenapetrosyan** [comment]
Not fixed, just experienced this exact issue twice in a row while developing. This is my first project with Firebase, and I have to say this doesn't give me confidence in the product. How often do things like this happen?

**Comment by narugami** [comment]
Also having one

**Comment by mapo-lp** [comment]
the issue is happening to me everyday .. somebody found a fix?

**Comment by Estayparadox** [comment]
In my case it happens the first time I try to login with Twitter in my iOS application.
The Swift method `Auth.auth().signInAndRetrieveData(with: AuthCredential, completion: AuthDataResultCallback?)` return this error:
`(2) Twitter Authentication Failed:  Malformed response cannot be parsed from twitter.com for VERIFY_CREDENTIAL`
Then the second time I try to login it works.

**Comment by snakajima** [comment]
It happens to me as well, not just occasionally but very often.

**Comment by narugami** [comment]
The best way is to stop using Firebase. I did.

**Comment by ljle** [comment]
This is happening to us on an app live in production with paying customers. @ronnieroyston's workaround didn't work, tried in various browsers and nothing. Clearing site data and cookies or incognito mode didn't work either, the Twitter Auth page isn't even reached, it just loads and goes back to the Firebase app and shows the "Malformed response cannot be parsed from twitter.com for OAUTH1_REQUEST_TOKEN" error. Even revoking access to the Firebase app from the Twitter account does not work. 

![image](https://user-images.githubusercontent.com/696474/107070784-85245800-67c2-11eb-8c36-6a828b90e68d.png)


Frankly, it's embarrassing this has been an issue for 4 years and there's no fix yet.

**Comment by Jood80** [comment]
any updates on this?

**Comment by avionics18** [comment]
Any updates?
