### ISSUE TITLE
firebaseui-dialog too tall on chrome

### ISSUE THREAD

**Issue by sumarlidason** [firebase/firebaseui-web#806]
### [REQUIRED] Describe your environment
```
  "firebase": "^8.2.4",
  "firebaseui": "^4.7.1",

  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.2
```

### [REQUIRED] Describe the problem
firebaseui dialog grows after sign-on success
<img width="1131" alt="Screen Shot 2021-01-28 at 12 21 19 PM" src="https://user-images.githubusercontent.com/1991770/106176784-bfa84800-6165-11eb-8e5a-eb8971303de3.png">

#### Steps to reproduce:

complete sign-on w/ link, enter email address to continue (don't press enter), over mouse over script debug "pause execution button", press enter and rapidly click pause button.

Open inspector to view DOM.

#### Relevant Code:
https://github.com/firebase/firebaseui-web/blob/540ddc0927920b0380fc9ba6d3f08d1377985fcc/stylesheet/firebase-ui.css#L375-L377

#### My interim fix
```
dialog.mdl-dialog.firebaseui-dialog.firebaseui-id-dialog {
  height: fit-content !important;
}
```

I haven't seen any side effects from overriding the height yet ~ but considering the comment already existing there ~ maybe implications elsewhere.

**Comment by samhorlbeck** [comment]
Hi, thanks for reaching out. Does it work if you set a max height on the element that contains Firebase UI in your app?

**Comment by sumarlidason** [comment]
The dialog mounts to the DOM root, and its style is manually calculated:
<img width="1012" alt="Screen Shot 2021-01-29 at 6 48 03 AM" src="https://user-images.githubusercontent.com/1991770/106272041-650efa80-61fe-11eb-8c3d-ca1a7d93e0f0.png">

adding `bottom: 'auto'` also prevents the downward shift ~
![image](https://user-images.githubusercontent.com/1991770/106273166-35f98880-6200-11eb-8b30-8c95532ec326.png)

🤷

**Comment by bojeil-google** [comment]
I looked into this issue. I tried it out in various browsers and Chrome v87 and it works as expected. This issue seems to manifest in Chrome v88. I speculate it is a bug in the latest version of Chrome.

**Comment by bojeil-google** [comment]
This should be fixed in the latest FirebaseUI-web release.

**Comment by orzcode** [comment]
This either isn't fixed, or the 'fix' seems to have developed a bug of its own.

In the latest version of Chrome as of today, this same dialog appears (for me) suddenly way over to the left of the screen, with seemingly random absolute position numbers:

![image](https://github.com/firebase/firebaseui-web/assets/71000311/d020ae2d-55d6-49cd-9c33-8ded4d9f4101)

![image](https://github.com/firebase/firebaseui-web/assets/71000311/b2ae42d7-fa5d-41aa-9f1e-4b1cda85f92c)

I'm unable to tame this beast as it appears as a dialog overlaid on top of the rest of the page, so doesn't respect the flexbox rules in the place it 'should' be appearing (I.E: in the firebase auth div container like a regular Google Sign-in does)
